### ISSUE TITLE
Distribution tracker

### ISSUE THREAD

**Issue by xxxserxxx** [xxxserxxx/gotop#68]
This ticket tracks the status of various mechanisms for distributing gotop.

## Distributions
- [ ] Windows: packaged, no distribution channel of which I'm aware
- [ ] OSX: Homebrew. Currently as a tap in xxxserxxx/homebrew-gotop. Homebrew/core needs to be updated.
- [X] Arch: AUR has been transferred.  gotop-git points to old repo and the maintainer has been contacted.
- [ ] Redhat: Needs info
- [ ] Debian: Needs info
- [ ] Alpine: [Needs effort](https://pkgs.alpinelinux.org/packages?name=gotop&branch=edge)
- [ ] Gentoo: [Needs effort](https://packages.gentoo.org/); gotop is not in Gentoo stdlib
- [ ] Slackware: Needs info

## Libraries
- [ ] Nix: [Needs effort](https://github.com/NixOS/nixpkgs/blob/ce9f1aaa39ee2a5b76a9c9580c859a74de65ead5/pkgs/tools/system/gotop/default.nix#L17).  gotop is in Nix 19.09
- [ ] Flatpack: [Needs effort](https://flathub.org). gotop is not in flathub.
- [ ] Snap: [Needs effort](https://snapcraft.io/search?q=gotop).  Snap rules are in the repository, and the Snapcraft library contains three entries for gotop.
- [ ] AppImage: [Needs effort](https://www.appimagehub.com). gotop is not in appimagehub.

## Articles / how-tos / links
- [ ] [Linoxide](https://linoxide.com/linux-how-to/gotop-tool-monitor-system-activity-linux/)

**Comment by tormath1** [comment]
Hi, 

For Gentoo, `gotop` has been added to the Guru overlay (https://github.com/gentoo/guru/commit/7556ef0da625367b40d5b0ce7cbd92141a3e5a81). 
> The goal of the GURU project is to create an official repository of new Gentoo packages that are maintained collaboratively by Gentoo users

If it's OK for you, I can open a PR to add a few lines about `gotop` installation on Gentoo.

**Comment by xxxserxxx** [comment]
@tormath1, that would be great.  What can I do to help?  Can you shoot me instructions for Gentoo so that I can add them to the README?

**Comment by tormath1** [comment]
I submitted a PR(https://github.com/xxxserxxx/gotop/pull/88), nothing to do on your side !
